######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 17 05:03:09 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += defender.h defender_canvas.h randomness.cpp
SOURCES += defender.cpp defender_canvas.cpp main.cpp randomness.cpp
